#!/usr/bin/env python3
"""Animation-rig write-back server. Serves the bench AND accepts POST /apply to write a tune
back into the codebase as CALL-SITE props (never mutating the component's own defaults).

Per-target config lives in TARGETS below (the skill fills this when rigging a component):
  - usage:   path to the generated <Component>.usage.tsx  (whole-file write; deterministic)
  - demo:    optional runnable demo to patch (list of (regex, replacement-template) pairs)
  - sidecar: optional JSON tune record
  - props:   ordered list of (knob-key -> JSX prop-name) for the usage file
Keep writes deterministic: whole-file for the usage/sidecar, targeted regex for a demo."""
import json, re, os, threading
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

RIG_DIR = os.path.dirname(os.path.abspath(__file__))
PORT = 8792

# ---- PER-TARGET CONFIG (skill fills this; demo below is a no-op sink) --------------------
TARGET = "demo"
USAGE_PATH   = ""     # e.g. ".../DiagonalBorderSweep.usage.tsx"
SIDECAR_PATH = ""     # e.g. ".../rig-tunes/diagonal-border-sweep.json"
DEMO_PATH    = ""     # e.g. ".../diagonal-border-sweep.html"
COMPONENT    = "Component"
# (knob-key, jsx-prop, kind)  kind in {"int","float","str"} -- "str" emits a quoted JSX prop
PROPS = [ ("stagger","stagger","float"), ("travel","travel","int"), ("rotate","rotate","int") ]
# demo patches: (regex, template-with-{knob keys})  applied against DEMO_PATH text
DEMO_PATCHES = []     # e.g. [(r"const LEAD_FINISH = [\\d.]+;", "const LEAD_FINISH = {leadFinish};")]
# -----------------------------------------------------------------------------------------

USAGE_TEMPLATE = '''// AUTO-GENERATED by the animation rig bench — tuned CALL-SITE props for {component}.
// Regenerated on every "Apply". Does NOT change the component's own defaults.
import {{ type ReactNode }} from "react";
import {component} from "./{component}";

export function {component}Tuned({{ current, next }}: {{ current: ReactNode; next: ReactNode }}) {{
  return (
    <{component}
      current={{current}}
      next={{next}}
{props}    />
  );
}}
'''

def numfmt(v, kind):
    if kind == "str":                      # colour / text knobs travel as strings
        return '"%s"' % str(v).replace('"', '\\"')
    v = float(v)
    return str(int(v)) if kind == "int" or v == int(v) else str(v)

def write_usage(k):
    def one(jsx, val, kind):
        # str knobs emit  prop="value" ; numeric knobs emit  prop={value}
        return "      " + jsx + ("=" + val if kind == "str" else "={" + val + "}") + "\n"
    lines = "".join(one(jsx, numfmt(k[key], kind), kind)
                    for key, jsx, kind in PROPS if key in k)
    with open(USAGE_PATH, "w", encoding="utf-8") as f:
        f.write(USAGE_TEMPLATE.format(component=COMPONENT, props=lines))

def patch_demo(k):
    if not (DEMO_PATH and DEMO_PATCHES):
        return False
    with open(DEMO_PATH, "r", encoding="utf-8") as f:
        s = f.read()
    for rx, tmpl in DEMO_PATCHES:
        s = re.sub(rx, tmpl.format(**{kk: numfmt(k[kk], kd) for kk, _, kd in PROPS if kk in k}), s)
    with open(DEMO_PATH, "w", encoding="utf-8") as f:
        f.write(s)
    return True

class H(SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw): super().__init__(*a, directory=RIG_DIR, **kw)
    def _json(self, code, obj):
        out = json.dumps(obj).encode()
        self.send_response(code); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(out))); self.end_headers(); self.wfile.write(out)
    def do_POST(self):
        path = self.path.split("?")[0]
        if path == "/shutdown":                 # UI "Quit" button → stop the server & exit
            self._json(200, {"ok": True, "stopping": True})
            threading.Thread(target=self.server.shutdown, daemon=True).start()
            return
        if path != "/apply":
            self.send_error(404); return
        try:
            n = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(n) or b"{}")
            k = body.get("knob", {})
            if not USAGE_PATH:
                raise ValueError("serve.py not configured for a target (USAGE_PATH empty) — this is the demo sink.")
            wrote = []
            if SIDECAR_PATH:
                os.makedirs(os.path.dirname(SIDECAR_PATH), exist_ok=True)
                with open(SIDECAR_PATH, "w", encoding="utf-8") as f: json.dump(body, f, indent=2)
                wrote.append(SIDECAR_PATH)
            write_usage(k); wrote.append(USAGE_PATH)
            if patch_demo(k): wrote.append(DEMO_PATH)
            base = os.path.commonpath([os.path.dirname(p) for p in wrote]) if len(wrote) > 1 else os.path.dirname(wrote[0])
            self._json(200, {"ok": True, "wrote": [os.path.basename(p) for p in wrote]})
        except Exception as e:
            self._json(500, {"ok": False, "error": str(e)})
    def log_message(self, *a): pass

if __name__ == "__main__":
    print(f"animation-rig write-back server on http://localhost:{PORT}  (target: {TARGET})")
    print(f"OPEN THE BENCH AT http://localhost:{PORT}/rig-bench.html -- not 127.0.0.1.")
    print("Bench and target must share a hostname or Chrome throttles the iframe rAF and the")
    print("preview freezes at frame one while still looking composed. See FAILURE_LOG.md.")
    ThreadingHTTPServer(("127.0.0.1", PORT), H).serve_forever()
